[server]
follow_symlink = false
browser = "default"

[keymap]
preset = "vim"
destructive_delete = true

[keymap.overrides]

[mcp]
presets = []

[mcp.mcpServers]

[formatting]
line_length = 79

[snippets]
include_default_snippets = true
custom_paths = []

[diagnostics]
sql_linter = true

[language_servers.pylsp]
enable_pydocstyle = false
enabled = true
enable_mypy = true
enable_pyflakes = false
enable_flake8 = false
enable_pylint = false
enable_ruff = true

[language_servers.basedpyright]

[language_servers.ty]
enabled = true

[experimental]

[display]
default_width = "full"
theme = "dark"
cell_output = "below"
code_editor_font_size = 14
default_table_page_size = 10
dataframes = "rich"
default_table_max_columns = 50
reference_highlighting = false

[save]
format_on_save = false
autosave = "after_delay"
autosave_delay = 1000

[runtime]
output_max_bytes = 8000000
default_sql_output = "auto"
default_auto_download = []
auto_reload = "off"
watcher_on_save = "lazy"
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
reactive_tests = true
auto_instantiate = false

[completion]
activate_on_typing = true
copilot = false

[package_management]
manager = "uv"

[ai]
rules = ""
inline_tooltip = false
mode = "manual"

[ai.models]
custom_models = []
displayed_models = []
