#
#  Path and Fpath for Server Machine
#

[plugins.server-path]
inline = '''
function _server_path() {
    typeset -gU path fpath

    path=(
        $path
        ${HOME}/.local/bin/server(N-/)
    )
    fpath=(
        $fpath
        ${HOME}/.local/bin/server(N-/)
    )
}
zsh-defer _server_path
'''

#
# Prompt for Server Machine
#

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

#
# Alias for Server Machine
#

[plugins.alias]
local = '~/.config/alias'
use = ['server.sh']
apply = ['source']

#
#
#

[plugins.cuda]
local = '~/.local/bin/server'
use = ['cuda.sh']
apply = ['source']

[plugins.ssh-agent]
local = "~/.local/bin/server"
use = ['ssh_agent.sh']
apply = ['source']
